In [ ]:
# 1)numpy .numpy is a tool box in paython.
#2)we work with numbers and arrays(collecton of same kind of element)
#3)full form of numpy is numerical phython
#4) if we use numpy we use key word: import number



In [1]:
import numpy

In [ ]:
!pip install numpy

In [ ]:
df=numpy.array([1,2,3,4,5])
print(df)

[1 2 3 4 5]


In [ ]:
# above example is called (1 dimension array)

In [ ]:
df=numpy.array([[1,2,3,4,5],[1,2,3,4,5]])
df

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [ ]:
# above example is called ( 2d array)

In [ ]:
df=numpy.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])
print(df)

[[[1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]]]


In [ ]:
df=numpy.array([
   [
       [1,2,3,4,5],
       [1,2,3,4,5]
   ],
   [
    [1,2,3,4,5],
     [1,2,3,4,5]
    ]])
print(df)

[[[1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]]]


In [ ]:
# to check how much dimension array

In [ ]:
arr1=numpy.array([1,2,3,4,5])
print(arr1.ndim)

1


In [ ]:
arra1=numpy.array([[1,2,3,4,5,],[1,2,3,4,5]])
print(arra1.ndim)

2


In [ ]:
arra1=numpy.array([[[1,2,3,4,5,],[1,2,3,4,5],[1,2,3,4,5,],[1,2,3,4,5]]])
print(arra1.ndim)

3


In [ ]:
arra1=numpy.array([])
print(arra1.ndim)

1


In [ ]:
arra1=numpy.array([[[[[[[[[[]]]]]]]]]])
print(arra1.ndim)

10


In [ ]:
array1=numpy.array([[1,2,3,4,5],[1,2,3,4,5]])
print(array1.size)

10


In [ ]:
array1=numpy.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])
print(array1.size)

20


In [ ]:
a=[1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [ ]:
arra1=numpy.array([1,2,3,4,5])
print(arra1)

[1 2 3 4 5]


In [ ]:
import numpy
arra1=numpy.array([1,2,3,4,5])
print(arra1+1)

[2 3 4 5 6]


In [ ]:
arra1=numpy.array([1,2,3,4,5])
print(arra1+2)

[3 4 5 6 7]


In [ ]:
arra1=numpy.array([1,2,3,4,5])
print(arra1+3)

[4 5 6 7 8]


In [ ]:
arra1=numpy.array([1,2,3,4,5])
print(arra1*2)

[ 2  4  6  8 10]


In [ ]:
arra1=numpy.array([1,2,3,4,5])
print(arra1*3)

[ 3  6  9 12 15]


In [ ]:
arra1=numpy.array([1,2,3,4,5])
print(arra1-3)

[-2 -1  0  1  2]


In [ ]:
import numpy
arr1=numpy.array([2,3,4])
arr2=numpy.array([2,3,4])
print(arr1+arr2)

[4 6 8]


In [ ]:
import numpy
arr1=numpy.array([2,3,4])
arr2=numpy.array([2,3,4])
res=numpy.concatenate((arr1,arr2))
print(res)


[2 3 4 2 3 4]


In [ ]:
# array
#concatenate
#size and ndim

In [ ]:
arr1=numpy.array([1,2,3,4,5])
print(arr1[2:4])

[3 4]


In [ ]:
arr1=numpy.array([1,2,3,4,5])
print(arr1[1:4])

[2 3 4]


In [ ]:
arr=numpy.random.rand(2,3)
print(arr)

[[0.00105909 0.84166472 0.18729628]
 [0.85157947 0.4737497  0.75119094]]


In [ ]:
arr=numpy.random.rand(2,3)
print(arr.ndim)

2


In [ ]:
arr=numpy.random.rand(4,3)
print(arr)

[[0.4266913  0.08422238 0.6634839 ]
 [0.45762991 0.15281349 0.91986372]
 [0.32312038 0.18838315 0.25186661]
 [0.10585715 0.02735338 0.05637671]]


In [ ]:
arr=numpy.random.rand(4,4)
print(arr.ndim)

2


In [ ]:
arr=numpy.random.rand(4,3)
newarr=numpy.round(arr)
print(newarr)

[[0. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [ ]:
arr=numpy.random.rand(4,3)
newarr=(arr*100).astype(int)
print(newarr)

[[32 99  7]
 [15 78  4]
 [ 4 68 41]
 [94 80 89]]


In [ ]:
import numpy
arr1=numpy.array([[11,22,13,40,53],[111,221,233,14,5]])
m =numpy.max(arr1)
print(m)

233


In [ ]:
import numpy
arr1=numpy.array([[11,22,13,40,53],[111,221,233,14,5]])
m =numpy.min(arr1)
print(m)

5


In [ ]:
import numpy
arr1=numpy.array([[10,20,30,40,50],[60,70,80,90,100]])
m =numpy.transpose(arr1)
print(m)

[[ 10  60]
 [ 20  70]
 [ 30  80]
 [ 40  90]
 [ 50 100]]


In [ ]:

arr1=numpy.array([[10,20,30,40,50],
                  [10,70,80,90,100]])
res=numpy.unique(arr1)
print(res.ndim)

1


In [ ]:
import numpy
arr1=numpy.array([[10,20,30,40,50],
                  [60,70,80,90,100]])
res=numpy.transpose(arr1)
print(res)

[[ 10  60]
 [ 20  70]
 [ 30  80]
 [ 40  90]
 [ 50 100]]


In [ ]:
arr1=numpy.array([10,20,30,40,50])
res=numpy.sum(arr1)
print(res)

150


In [ ]:
# axis 1=row wise

In [ ]:
arr1=numpy.array([[10,20],[30,40,]])
res=numpy.sum(arr1,axis=1)
print(res)

[30 70]


In [ ]:
#axis 0 coum wise

In [ ]:
arr1=numpy.array([[10,20],
                 [30,40,]])
res=numpy.sum(arr1,axis=0)
print(res)

[40 60]


In [ ]:
arr1=numpy.array(
    [[10,20],
     [30,40]
     ]
    )
print(arr1[0])

[10 20]


In [ ]:
arr1=numpy.array(
    [[10,20],
     [30,40]
     ]
    )
print(arr1[1])

[30 40]


In [ ]:
arr1=numpy.array(
    [[10,20],
     [30,40]
     ]
    )
print(arr1[0,1])

20


In [ ]:
arr1=numpy.array(
    [[10,20],
     [30,40]
     ]
    )
print(arr1[1,1])

40


In [ ]:
arr1=numpy.array(
    [[10,20],
     [30,40]
     ]
    )
print(arr1[1,0])

30


In [ ]:
#task give by sir while doing class

In [ ]:
arr1=numpy.array([[[11,22,3,4,5],
                   [1,32,43,4,5]],

                  [[1,42,63,74,5],
                   [1,2,3,4,5]]])
print(arr1[1,0,2])

63


In [ ]:
arr=numpy.zeros((4,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr=numpy.ones((3,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
arr=numpy.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
arr=numpy.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [ ]:
arr=numpy.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [ ]:
import numpy
arr=numpy.arange(0,20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
arr=numpy.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
arr=numpy.arange(0,20)
res=arr.reshape(2,10,)
print(res)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [ ]:
arr1=numpy.array([100,20,300,14,50])
arr=numpy.sort(arr1)
print(arr)

[ 14  20  50 100 300]


In [ ]:
arr= numpy.zeros([1,1])
print(arr)

[[0.]]


In [ ]:
res=numpy.eye(3)
print(res)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr=numpy.array([1,2,3,4,5,6,7,8,9])
arr=arr.sum()
print(arr)

45


In [ ]:
import matplotlib.pyplot as mp

In [ ]:
#task for array by sir

In [ ]:
arr=numpy.array([0,1,2,3,4,5,6,7,8,9])
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr=numpy.random.rand(3,3)
print(arr)

[[0.79033067 0.72784884 0.52703776]
 [0.68492628 0.97668272 0.98362012]
 [0.56265311 0.69569274 0.82203364]]


In [ ]:
arr=numpy.array([0,1,2,3,4,5,6,7,8,9])
res=min(arr)
print(res)

0


In [ ]:
#5th question dont know

In [ ]:
#6th question dont know

In [ ]:
arr=numpy.array([0,1,2,3,4,5,6,7,8,9])
res=arr.reshape(2,5)
print(res)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
arr=numpy.array([[0,1,2,3,4],
                 [5,6,7,8,9]])
res=arr.flatten()
print(res)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr=numpy.array([1,2,3,4,])
res=numpy.diag(arr)
print(res)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
import numpy
a=numpy.array([0,1,2,3,4,5,6,7,8])
b=numpy.array([0,2,3,4,5,6,7,8,9])
res=a*b
print(res)

[ 0  2  6 12 20 30 42 56 72]


In [ ]:
import numpy as np
A = np.array([[3, 3, 3],
              [6, 6, 6]])
B = np.array([[1, 3],
              [2, 4],
              [3, 5]])
result = A @ B

print(result)


[[18 36]
 [36 72]]


In [ ]:
a=numpy.array([[3,4,5,],
            [6,7,8]])
b=numpy.array([[1,3],
               [4,5],
               [6,7]])
res=a@b
print(res)

[[ 49  64]
 [ 82 109]]


In [ ]:
arr=numpy.zeros((2,3))
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr=numpy.ones((3,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
a=numpy.array([0,1,2,3,4])
b=numpy.array([5,6,7,8,9])
res=numpy.concatenate((a,b))
print(res)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy
arr1=numpy.array([[10,20,30,40,50],[60,70,80,90,100]])
m =numpy.transpose(arr1)
print(m)

In [ ]:
arr1=numpy.array([[0,1,2,],
                  [3,4,5],
                  [6,7,8]])
res=numpy.transpose(arr1)
print(res)


[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [ ]:
import numpy
arr=numpy.array([1,2,3,4,5,6,7,8])
res=numpy.sort((arr))
print(res[::-1])

[8 7 6 5 4 3 2 1]


In [ ]:
import numpy
arr=numpy.array([1,2,3,4,5,6,7,5,8,4,5,7,9,8])
res=numpy.unique((arr))
print(res)

[1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy
arr=numpy.array([1,2,3,4,2,4,3,5,4,5,7,8,7,8,9])
res=numpy.unique(arr)
print(res)

[1 2 3 4 5 7 8 9]


In [2]:
import numpy as np

# Original array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Replace all odd numbers with -1
arr[arr % 2 != 0] = -1

print(arr)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [5]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr[1::2]=-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
import numpy as np
celsius = np.array([0, 10, 20, 30, 40])
fahrenheit = celsius * 9/5 + 32
print(fahrenheit)


In [6]:
a=numpy.array([0,10,20,30,40,50])
f=a*9/5+32
print(f)

[ 32.  50.  68.  86. 104. 122.]
